### ISSUE TITLE
Help in Android. Not loading on Android

### ISSUE THREAD

**Issue by clmorales** [arjendeblok/aurelia-cordova-skeleton#2]
First of all thank you for taking your time and sharing this.  For some reason when I try to run it on Android 'cordova emulate android'  it does not show the 'Hello Cordova' string.  Only the 'booting...' string is shown.  It works find if I run it on the browser 'cordova run browser'.

**Comment by arjendeblok** [comment]
Duplicate of #1.
But while the issue was closed, this issue was not yet solved.

**Comment by clmorales** [comment]
Thank a lot.  This solution works for me.
